name: flutter_slice_one
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^3.0.3
  http: ^0.12.0+1
  rxdart: ^0.18.0
  shared_preferences: ^0.5.2
  countdown: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - flutter_logo_round.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf
